// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GenerateGuidService.Models;

public partial class PlanningContext : DbContext
{
    public PlanningContext()
    {
    }

    public PlanningContext(DbContextOptions<PlanningContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tasks> Tasks { get; set; }

   // protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
   //=> optionsBuilder.UseSqlServer("Data Source=DESKTOP-C1MT787;Initial Catalog=Planning;Persist Security Info=True;User ID=sa;Password=sql;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //modelBuilder.Entity<Tasks>(entity =>
        //{
        //    entity.Property(e => e.State).IsFixedLength();
        //});

        //OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}